In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

%matplotlib inline
%config InlineBackend.figure_format='retina'
sns.set(style='whitegrid', palette='muted', font_scale=1.5)
rcParams['figure.figsize'] = 16, 10


In [2]:
df = pd.read_csv('merged_Floor1.csv', index_col='Date', parse_dates=True)

In [3]:
dataset=pd.DataFrame(columns=['lights','acs','plug'])
dataset

Empty DataFrame
Columns: [lights, acs, plug]
Index: []

In [4]:
dataset['lights']=df['z1_Light(kW)']+df['z2_Light(kW)']+df['z3_Light(kW)']+df['z4_Light(kW)']
dataset['acs']=df['z2_AC1(kW)']+df['z2_AC2(kW)']+df['z2_AC3(kW)']+df['z2_AC4(kW)']
dataset['plug']=df['z1_Plug(kW)']+df['z2_Plug(kW)']+df['z3_Plug(kW)']

In [5]:
dataset['Power_consumption']=dataset['lights']+dataset['acs']+dataset['plug']

In [6]:
dataset=dataset.fillna(method="ffill")

In [7]:
final_df=dataset

In [8]:
from numpy import array
dataset=np.array(dataset)

In [9]:
n_step=1
lags=7

In [10]:
def to_supervised(train,n_input,n_out):
    #falten data
    data=train
    X,y=list(),list()
    in_start=0
    for _ in range(len(data)):
        in_end=in_start+ n_input
        out_end=in_end + n_out
        if out_end<=len(data):
            x_input=data[ in_start:in_end,0]
            x_input=x_input.reshape((len(x_input)))
            X.append(x_input)
            y.append(data[in_end:out_end,0])
        in_start+=1
    return array(X), array(y) 

In [11]:
import pandas as pd
import numpy as np
mon=final_df.resample('M').mean() #Month wise consideration


In [12]:
mon

lights        acs       plug  Power_consumption
Date                                                          
2018-07-31  61.979513  38.351035  25.586273         125.931828
2018-08-31  66.392066  37.827817  32.570205         155.822944
2018-09-30  59.846756  33.221278  26.333554         135.985362
2018-10-31  62.814795  31.327017  18.728826         112.885245
2018-11-30  60.542504  28.833471  18.390561         107.769779
2018-12-31  59.706976  32.875259  15.912541         108.498589
2019-01-31  58.919683  27.550707  16.719073         103.191115
2019-02-28  54.953642  34.170970  15.798198         104.923820
2019-03-31  47.769112  33.689731  16.829733          98.290916
2019-04-30  44.405893  40.919247  19.593903         104.922686
2019-05-31  49.167417  46.735830  20.926883         116.832495
2019-06-30  50.128827  40.955397  21.578297         112.665660
2019-07-31  53.309234  33.332232  17.173070         103.814457
2019-08-31  55.603635  33.027976  17.183197         105.817908
2019-09-30  50.239055  27.148718  14.404016          91.853963
2019-10-31  52.011799  30.394991  16.376754          98.785242
2019-11-30  51.903082  23.176353  18.992381          94.077244
2019-12-31  49.451837  23.173616  16.547840          89.176754

In [13]:
from numpy import array
mon=np.array(mon)

In [14]:
X,y=to_supervised(mon,n_input=lags,n_out=n_step)

In [15]:
from keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
# Encode class values as integers and perform one-hot-encoding
encoder = LabelEncoder()
encoder.fit(y)
y = encoder.transform(y)
y = np_utils.to_categorical(y)
print(y)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


c:\Users\Indra Namala\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Indra Namala\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
from sklearn.model_selection import train_test_split
# shuffle and split training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=0)
# Multi Layer Perceptron Artificial Neural Network
from sklearn.neural_network import MLPClassifier 



In [21]:
mlp_gs = MLPClassifier(max_iter=100)
parameter_space = {
    'hidden_layer_sizes': [(10,30,10),(20,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(mlp_gs, parameter_space, n_jobs=-1, cv=5)
clf.fit(X_train, y_train) # X is train samples and y is the corresponding labels

c:\Users\Indra Namala\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


GridSearchCV(cv=5, estimator=MLPClassifier(max_iter=100), n_jobs=-1,
             param_grid={'activation': ['tanh', 'relu'],
                         'alpha': [0.0001, 0.05],
                         'hidden_layer_sizes': [(10, 30, 10), (20,)],
                         'learning_rate': ['constant', 'adaptive'],
                         'solver': ['sgd', 'adam']})

In [22]:
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (10, 30, 10), 'learning_rate': 'constant', 'solver': 'sgd'}


In [19]:
means = clf.cv_results_['mean_test_score']
stds = clf.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, clf.cv_results_['params']):
    print("%0.3f (+/-%0.03f) for %r" % (mean, std * 2, params))

0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (10, 30, 10), 'learning_rate': 'constant', 'solver': 'sgd'}
0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (10, 30, 10), 'learning_rate': 'constant', 'solver': 'adam'}
0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (10, 30, 10), 'learning_rate': 'adaptive', 'solver': 'sgd'}
0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (10, 30, 10), 'learning_rate': 'adaptive', 'solver': 'adam'}
0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (20,), 'learning_rate': 'constant', 'solver': 'sgd'}
0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (20,), 'learning_rate': 'constant', 'solver': 'adam'}
0.000 (+/-0.000) for {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': (20,), 'learning_rate': 'adaptive', 'solver': 'sgd'}
0.000 (+/-0.000) 

In [23]:
mlp = MLPClassifier(hidden_layer_sizes=(10, 30, 10), activation='tanh', solver='sgd', 
                    alpha=0.0001, batch_size=16, learning_rate='constant', learning_rate_init=0.005, 
                    power_t=0.5, max_iter=9, shuffle=True, random_state=11, tol=0.00001, 
                    verbose=True, warm_start=False, momentum=0.8, nesterovs_momentum=True, 
                    early_stopping=False, validation_fraction=0.2, 
                    beta_1=0.9, beta_2=0.999, epsilon=1e-08)
print(mlp)

MLPClassifier(activation='tanh', batch_size=16, hidden_layer_sizes=(10, 30, 10),
              learning_rate_init=0.005, max_iter=9, momentum=0.8,
              random_state=11, solver='sgd', tol=1e-05, validation_fraction=0.2,
              verbose=True)


In [25]:
history_mlp=mlp.fit(X_train,y_train)

Iteration 1, loss = 8.45093764
Iteration 2, loss = 8.21551079
Iteration 3, loss = 7.66248397
Iteration 4, loss = 7.30396909
Iteration 5, loss = 6.89280176
Iteration 6, loss = 6.47647492
Iteration 7, loss = 6.11950642
Iteration 8, loss = 5.84483969
Iteration 9, loss = 5.63595955


c:\Users\Indra Namala\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:621: UserWarning: Got `batch_size` less than 1 or larger than sample size. It is going to be clipped
  warnings.warn(
c:\Users\Indra Namala\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (9) reached and the optimization hasn't converged yet.
  warnings.warn(


In [26]:
y_pred = mlp.predict(X_test)

In [27]:
y_pred

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])